### ISSUE TITLE
School.yml not found

### ISSUE THREAD

**Issue by GjjvdBurg** [autolab/autolab-oneclick#4]
Hi there,

I'm testing the one-click install and the installation fails at the precompilation of the Rails assets, with the error that the file ``/home/app/webapp/config/school.yml`` can't be found. This could be a documentation error (one-click install docs don't mention it) or with the installation script (``server/Autolab/bin/setup.sh`` is supposed to copy it but is never called).

Thanks!

**Comment by nayak16** [comment]
Hello @GjjvdBurg we have pushed a fix for this in master. Please pull the latest master and let us know if you have any further issues

**Comment by GjjvdBurg** [comment]
@nayak16 Thanks!
